### ISSUE TITLE
Add latest MariaDB support instead of MySQL

### ISSUE THREAD

**Issue by reypm** [million12/docker-nginx-php#14]
@ryzy I would like to drop MySQL support and add support for MariaDB but I have a problem: how to deal with `mysql_secure_installation` which is intended to be interactive. I am following [this guide](https://www.linode.com/docs/databases/mariadb/how-to-install-mariadb-on-centos-7) but that I mention is my only concern, can you help me out a bit?

Also is a good practice to keep database files inside the docker container or would be fine to share in some volumes under the host? What do you think?

PS: If you can take a look to the fork I have created from this repo and see the new lines removing MySQL from default and adding MariaDB and let me know your toughs.

**Comment by ryzy** [comment]
Hi,

The `mysql` in yum repos is already for a while alias for `mariadb`. So in fact the MariaDB _client_ is installed in this image already. And can be used to connect to any MariaDB instances.

Did you consider using another container with MariaDB? It's easy, you just link this container and mariadb, provide appropriate host name in your app and that's all. Having an application and MariaDB server (and god knows what else) in one container is considered as antipattern and monolithic approach, hard to maintain and update.

Anyway, we have our [million12/mariadb](https://github.com/million12/docker-mariadb) which you can use for inspiration if you look how to install it inside container. But I definitely recommend using it as a separate container - easier than trying to embed MariaDB inside this one ;)

Hope it helps.
Marcin

**Comment by reypm** [comment]
Hi there @ryzy you're right, would be better to use them separately. I did know docker compose does this, do you have any compose integrating all those tools? What about volumes? I've started this docker container and doesn't see any mapped volume or maybe I am missing something. Wouldn't be better to have our files under the host?

**Comment by reypm** [comment]
@ryzy I would be very grateful if you help me out to build a `docker compose` of those two meaning this repository and mariadb one. My idea would be put them together in a same directory and then create a `docker-compose.yml` file like for example:

```
version: '2'
services:
    db:
        build: ./docker-mariadb
    php-nginx:
        build: ./docker-nginx-php
        links:
            - db
```

I don't know if this is right or I need to add anything else, what do you think? Could you help me a bit?

**Comment by pozgo** [comment]
Below a simple example od `docker-compose.yml` file which will deploy three docker  images. 
- Database Data container for easy backup of your database files 
- Database itself
- Nginx server which is linked to database container

```
version: '2'
services:
  db-data:
    container_name: db-data
    image: busybox:latest
    volumes:
      - /data/mysql-db:/var/lib/mysql

  db:
    container_name: db
    image: million12/mariadb
    restart: always
    volumes_from:
      - db-data
    environment:
      - MARIADB_PASS=MyPassword

  nginx:
    container_name: nginx
    image: million12/nginx-php
    restart: always
    links:
      - db:maria.db
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NGINX_GENERATE_DEFAULT_VHOST=true
```

After logging in into nginx container you can connect to MariaDB  database under maria.db address 

`docker exec -ti nginx bash`  
Inside the conteiner   

`mysql -u admin -pMyPassword -h maria.db`

**Comment by reypm** [comment]
Thanks @pozgo that's helpful. I have one question, where I should place my project files in the nginx container? I mean under mariadb I've see a volume but under nginx I didn't any advice? For example in [this docker-compose.yml](https://github.com/eko/docker-symfony/blob/master/docker-compose.yml) I am seeing some volumes for php and nginx where I should place my code. Which is the right place in this case?

**Comment by pozgo** [comment]
@reypm I think this is more Nginx related question. I believe you can put your files whenever you like. Just need to make sure that your custom Nginx config file is correct. 

[here](https://github.com/million12/docker-nginx-php/blob/master/container-files/config/init/vhost-default.conf) you have an example of our default virtual host file config file. See `root` section on line `6` 

By default, this image is using `/data/www` directory. See [Readme](https://github.com/million12/docker-nginx-php/blob/master/README.md) file, section `Directory structure inside image`

PS. Usually, I'm using this image ad base image for more complex projects. I'm adding then my own modifications when the image is built. Then I'm using git to fetch latest version of my PHP application inside the container when the container is actually run.

**Comment by reypm** [comment]
Great @pozgo so that section on the Readme says that I will have those volumes available or I should add them to the `docker-compose.yml` file as you did  for the `db-data` container?

**Comment by pozgo** [comment]
@reypm Yes, I believe that directory is available. But remember that this is only our own default settings created for the purpose of quick test if the image is running properly. 

As an example please see my [Cacti docker](https://github.com/pozgo/docker-cacti) image that is based on this very nginx-php image. I have added my own modifications and I think I even changed the default directories.

**Comment by reypm** [comment]
Ok @pozgo and after get the `docker-compose.yml` file is jut run `docker-compose up`? If so I am getting a weird issue :-\

**Comment by pozgo** [comment]
@reypm There was a typo in `docker-compose.yml`. Should be ok now.

**Comment by reypm** [comment]
@pozgo is not, I am getting this output:

```
$ docker-compose up
Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 9, in <module>
    load_entry_point('docker-compose==1.7.1', 'console_scripts', 'docker-compose')()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 547, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2720, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2380, in load
    return self.resolve()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2386, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/site-packages/compose/cli/main.py", line 14, in <module>
    from . import errors
  File "/usr/lib/python2.7/site-packages/compose/cli/errors.py", line 9, in <module>
    from docker.errors import APIError
  File "/usr/lib/python2.7/site-packages/docker/__init__.py", line 20, in <module>
    from .client import Client, AutoVersionClient, from_env # flake8: noqa
  File "/usr/lib/python2.7/site-packages/docker/client.py", line 19, in <module>
    import requests
  File "/usr/lib/python2.7/site-packages/requests/__init__.py", line 61, in <module>
    from .packages.urllib3.exceptions import DependencyWarning
ImportError: cannot import name DependencyWarning
```

**Comment by pozgo** [comment]
What version of docker and docker-compose are you using? 
Run:
`docker version` 
and 
`docker-compose version`
and paste the output. 

It seems to me that you have mismatched docker and docker-compose versions.

See [Docker Compose Docs](https://github.com/docker/compose/releases/tag/1.7.1)

**Comment by reypm** [comment]
@pozgo here ....

```
$ docker version
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:39:21 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:39:21 2016
 OS/Arch:      linux/amd64
```

The second command for docker-compose give me the same issue

**Comment by pozgo** [comment]
Ok... What OS you are running it on? 
If MacOS do not install docker-compose from `brew` or `MacPorts`. Fetch if from [official GitHub repo](https://github.com/docker/compose/releases/tag/1.7.1) instead. Or use [Docker for Mac Beta](https://beta.docker.com/).

**Comment by reypm** [comment]
I am using Fedora 24 4.6.3-300.fc24.x86_64 and I've followed the steps from [here](https://docs.docker.com/engine/installation/linux/fedora/).

**Comment by pozgo** [comment]
How did you install `docker-compose`?

If it's from yum repo delete it.
`yum remove docker-compose`

then according to offcial Docker Compose GitHub repo.

```
curl -L https://github.com/docker/compose/releases/download/1.7.1/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose

```

**Comment by reypm** [comment]
I don't remember how did I installed but here is what I did:

```
$ sudo dnf remove docker-compose
No match for argument: docker-compose
Error: No packages marked for removal.

// Not found let's update DB
$ sudo updatedb
$ locate docker-compose
/home/rperez/Downloads/web-development/docker-compose.yml
/usr/bin/docker-compose

// Remove from /usr/bin/docker-compose
rm -f /usr/bin/docker-compose

// Re-install using ...
curl -L https://github.com/docker/compose/releases/download/1.7.1/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose

// try to run the command
$ docker-compose 
bash: /usr/bin/docker-compose: No such file or directory
```

**Comment by pozgo** [comment]
It was downloaded into different directory ;) 

`sudo mv /usr/local/bin/docker-compose /usr/bin/docker-compose`

**Comment by reypm** [comment]
Yeah, @pozgo now is working thanks, I will leave this ticket open for a while until I am trying this and will close as soon as I get this working, thanks both for your guidance and nice work

**Comment by pozgo** [comment]
Excellent. :) NP.

**Comment by reypm** [comment]
@pozgo take a look to the following pics:

![2016-07-05_18-18-16](https://cloud.githubusercontent.com/assets/627886/16601767/04504ad6-42dd-11e6-9672-7e525b5479ff.png)
![2016-07-05_18-18-35](https://cloud.githubusercontent.com/assets/627886/16601768/0454bb34-42dd-11e6-8d6d-2b7dc4db9954.png)
![2016-07-05_18-18-43](https://cloud.githubusercontent.com/assets/627886/16601766/044fa91e-42dd-11e6-8eeb-9583197f5f98.png)

Is that output right to you? I am not seeing any `/data/mysql-db` mapped and cmd just stop there

**Comment by reypm** [comment]
@pozgo I've both containters running :smirk: but I don't know how to connect from MySQL Workbench to the container for import the oldest DB backup that I had, how I can achieve this?

BTW, here is the `docker-compose.yml` with some modifications for VOLUMES:

```
version: '2'
services:
  db-data:
    container_name: db-data
    image: busybox:latest
    volumes:
      - ./data/mysql-db:/var/lib/mysql

  db:
    container_name: db
    image: million12/mariadb
    restart: always
    volumes_from:
      - db-data
    environment:
      - MARIADB_PASS=1qazxsw2

  nginx:
    container_name: nginx
    image: million12/nginx-php
    restart: always
    depends_on:
      - db
    links:
      - db:maria.db
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/www:/data/www
      - ./data/www/default:/data/www/default
      - ./data/logs:/data/logs
      - ./data/tmp/php:/data/tmp/php
    environment:
      - NGINX_GENERATE_DEFAULT_VHOST=true

```
