### ISSUE TITLE
Install php-pecl-yaml ext for PHP 7

### ISSUE THREAD

**Issue by ryzy** [million12/docker-nginx-php#7]
Be aware of that issue: https://github.com/million12/docker-nginx-php/pull/6
Can be installed once we sure it's resolved.

**Comment by dimaip** [comment]
This is the file that was giving me segfaults:

```
blah: &alohaPlain
  placeholder: 'Text is here'
  format:
    b: FALSE
'Sfi.Sfi:PagePresentation':
  superTypes:
    'Sfi.Sfi:AbstractPage': true
  properties:
    lead:
      type: string
      ui:
        aloha:
          <<: *alohaRich
          placeholder: Лид
```

Full file: https://github.com/sfi-ru/SfiDistr/blob/master/Packages/Sites/Sfi.Sfi/Configuration/NodeTypes.Pages.yaml
